'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Assignment.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AddItem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddItem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AddOrder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddOrder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AddUser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddUser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Apple_Calamasi_Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Apple_Calamasi_Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Archive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Archive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Back1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Barley_Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barley_Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property BFIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("BFIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BFLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BFLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bihun_Goreng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bihun_Goreng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BillAndPayment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillAndPayment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cappucino_Blended() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cappucino_Blended", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cham_Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cham_Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chicken_Wings_with_Fries() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chicken_Wings_with_Fries", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Curry_Puff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Curry_Puff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DefaultProfile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DefaultProfile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [LocalizedFileNames]
        '''Screenshot 2025-04-04 153925.png=@Screenshot 2025-04-04 153925,0
        '''Screenshot 2025-04-24 202000.png=@Screenshot 2025-04-24 202000,0
        '''Screenshot 2025-04-24 202106.png=@Screenshot 2025-04-24 202106,0
        '''Screenshot 2025-04-24 202100.png=@Screenshot 2025-04-24 202100,0
        '''Screenshot 2025-04-24 202047.png=@Screenshot 2025-04-24 202047,0
        '''Screenshot 2025-04-24 202043.png=@Screenshot 2025-04-24 202043,0
        '''Screenshot 2025-04-24 202039.png=@Screenshot 2025-04-24 202039,0
        '''Screenshot 2025-04-24 202031 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property desktop() As String
            Get
                Return ResourceManager.GetString("desktop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property French_Fries() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("French_Fries", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property French_Toast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("French_Toast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Honey_Lemon_Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Honey_Lemon_Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hot_Barley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hot_Barley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hot_Cham() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hot_Cham", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hot_Honey_Lemon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hot_Honey_Lemon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hot_Kopi_O() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hot_Kopi_O", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hot_Milk_Tea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hot_Milk_Tea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Hot_Milo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hot_Milo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ItemStock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ItemStock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Limau_Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Limau_Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login_profile_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_profile_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Longan_Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Longan_Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lychee_Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lychee_Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maggi_Goreng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maggi_Goreng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maggi_Kari_Sup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maggi_Kari_Sup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mee_Goreng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mee_Goreng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mee_Rebus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mee_Rebus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Milo_Dinosaur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Milo_Dinosaur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Murtabak_Ayam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Murtabak_Ayam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nasi_Briyani_with_Rendang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nasi_Briyani_with_Rendang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nasi_Goreng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nasi_Goreng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nasi_Goreng_Pattaya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nasi_Goreng_Pattaya", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nasi_Lemak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nasi_Lemak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nugget_with_Fries() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nugget_with_Fries", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Order() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Order", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Plain_Water() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Plain_Water", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Potato_Wedges() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Potato_Wedges", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rojak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rojak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Roti_Bom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Roti_Bom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Roti_Cheese() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Roti_Cheese", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Roti_Kosong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Roti_Kosong", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Roti_Pisang() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Roti_Pisang", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Roti_Planta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Roti_Planta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Roti_Sardin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Roti_Sardin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Roti_Telur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Roti_Telur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Roti_Tisu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Roti_Tisu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SearchUser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SearchUser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Snap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Snap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Staff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Staff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Teh_Ais() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teh_Ais", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Telur_Dadar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Telur_Dadar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrackStock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrackStock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WelcomePage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WelcomePage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
