<?xml version="1.0" encoding="utf-8"?><Database Name="BL-fariz" Class="BL_farizDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\BL-fariz.mdf;Integrated Security=True" SettingsObjectName="Assignment.My.MySettings" SettingsPropertyName="BL_FarizConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TableNo" Member="TableNos">
    <Type Name="TableNo">
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="X" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Y" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Color" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>