'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="BL-Fariz-")>  _
Partial Public Class BL_farizDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertItem(instance As Item)
    End Sub
  Partial Private Sub UpdateItem(instance As Item)
    End Sub
  Partial Private Sub DeleteItem(instance As Item)
    End Sub
  Partial Private Sub InsertTableNo(instance As TableNo)
    End Sub
  Partial Private Sub UpdateTableNo(instance As TableNo)
    End Sub
  Partial Private Sub DeleteTableNo(instance As TableNo)
    End Sub
  Partial Private Sub InsertOrder(instance As [Order])
    End Sub
  Partial Private Sub UpdateOrder(instance As [Order])
    End Sub
  Partial Private Sub DeleteOrder(instance As [Order])
    End Sub
  Partial Private Sub InsertOrder_Item(instance As Order_Item)
    End Sub
  Partial Private Sub UpdateOrder_Item(instance As Order_Item)
    End Sub
  Partial Private Sub DeleteOrder_Item(instance As Order_Item)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Assignment.My.MySettings.Default.BL_Fariz_ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Items() As System.Data.Linq.Table(Of Item)
		Get
			Return Me.GetTable(Of Item)
		End Get
	End Property
	
	Public ReadOnly Property TableNos() As System.Data.Linq.Table(Of TableNo)
		Get
			Return Me.GetTable(Of TableNo)
		End Get
	End Property
	
	Public ReadOnly Property Orders() As System.Data.Linq.Table(Of [Order])
		Get
			Return Me.GetTable(Of [Order])
		End Get
	End Property
	
	Public ReadOnly Property Order_Items() As System.Data.Linq.Table(Of Order_Item)
		Get
			Return Me.GetTable(Of Order_Item)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Item")>  _
Partial Public Class Item
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Item_Id As String
	
	Private _Item_Name As String
	
	Private _Item_Category As String
	
	Private _Item_Price As Decimal
	
	Private _Item_Description As String
	
	Private _Item_Quantity As Integer
	
	Private _Item_StockLvl As String
	
	Private _Item_Picture As System.Data.Linq.Binary
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnItem_IdChanging(value As String)
    End Sub
    Partial Private Sub OnItem_IdChanged()
    End Sub
    Partial Private Sub OnItem_NameChanging(value As String)
    End Sub
    Partial Private Sub OnItem_NameChanged()
    End Sub
    Partial Private Sub OnItem_CategoryChanging(value As String)
    End Sub
    Partial Private Sub OnItem_CategoryChanged()
    End Sub
    Partial Private Sub OnItem_PriceChanging(value As Decimal)
    End Sub
    Partial Private Sub OnItem_PriceChanged()
    End Sub
    Partial Private Sub OnItem_DescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnItem_DescriptionChanged()
    End Sub
    Partial Private Sub OnItem_QuantityChanging(value As Integer)
    End Sub
    Partial Private Sub OnItem_QuantityChanged()
    End Sub
    Partial Private Sub OnItem_StockLvlChanging(value As String)
    End Sub
    Partial Private Sub OnItem_StockLvlChanged()
    End Sub
    Partial Private Sub OnItem_PictureChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnItem_PictureChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Id", DbType:="VarChar(7) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property Item_Id() As String
		Get
			Return Me._Item_Id
		End Get
		Set
			If (String.Equals(Me._Item_Id, value) = false) Then
				Me.OnItem_IdChanging(value)
				Me.SendPropertyChanging
				Me._Item_Id = value
				Me.SendPropertyChanged("Item_Id")
				Me.OnItem_IdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Name", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property Item_Name() As String
		Get
			Return Me._Item_Name
		End Get
		Set
			If (String.Equals(Me._Item_Name, value) = false) Then
				Me.OnItem_NameChanging(value)
				Me.SendPropertyChanging
				Me._Item_Name = value
				Me.SendPropertyChanged("Item_Name")
				Me.OnItem_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Category", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property Item_Category() As String
		Get
			Return Me._Item_Category
		End Get
		Set
			If (String.Equals(Me._Item_Category, value) = false) Then
				Me.OnItem_CategoryChanging(value)
				Me.SendPropertyChanging
				Me._Item_Category = value
				Me.SendPropertyChanged("Item_Category")
				Me.OnItem_CategoryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Price", DbType:="Decimal(10,2) NOT NULL")>  _
	Public Property Item_Price() As Decimal
		Get
			Return Me._Item_Price
		End Get
		Set
			If ((Me._Item_Price = value)  _
						= false) Then
				Me.OnItem_PriceChanging(value)
				Me.SendPropertyChanging
				Me._Item_Price = value
				Me.SendPropertyChanged("Item_Price")
				Me.OnItem_PriceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Description", DbType:="VarChar(500) NOT NULL", CanBeNull:=false)>  _
	Public Property Item_Description() As String
		Get
			Return Me._Item_Description
		End Get
		Set
			If (String.Equals(Me._Item_Description, value) = false) Then
				Me.OnItem_DescriptionChanging(value)
				Me.SendPropertyChanging
				Me._Item_Description = value
				Me.SendPropertyChanged("Item_Description")
				Me.OnItem_DescriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Quantity", DbType:="Int NOT NULL")>  _
	Public Property Item_Quantity() As Integer
		Get
			Return Me._Item_Quantity
		End Get
		Set
			If ((Me._Item_Quantity = value)  _
						= false) Then
				Me.OnItem_QuantityChanging(value)
				Me.SendPropertyChanging
				Me._Item_Quantity = value
				Me.SendPropertyChanged("Item_Quantity")
				Me.OnItem_QuantityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_StockLvl", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property Item_StockLvl() As String
		Get
			Return Me._Item_StockLvl
		End Get
		Set
			If (String.Equals(Me._Item_StockLvl, value) = false) Then
				Me.OnItem_StockLvlChanging(value)
				Me.SendPropertyChanging
				Me._Item_StockLvl = value
				Me.SendPropertyChanged("Item_StockLvl")
				Me.OnItem_StockLvlChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Picture", DbType:="VarBinary(MAX)", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Item_Picture() As System.Data.Linq.Binary
		Get
			Return Me._Item_Picture
		End Get
		Set
			If (Object.Equals(Me._Item_Picture, value) = false) Then
				Me.OnItem_PictureChanging(value)
				Me.SendPropertyChanging
				Me._Item_Picture = value
				Me.SendPropertyChanged("Item_Picture")
				Me.OnItem_PictureChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.TableNo")>  _
Partial Public Class TableNo
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Name As String
	
	Private _X As System.Nullable(Of Integer)
	
	Private _Y As System.Nullable(Of Integer)
	
	Private _Color As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnNameChanging(value As String)
    End Sub
    Partial Private Sub OnNameChanged()
    End Sub
    Partial Private Sub OnXChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnXChanged()
    End Sub
    Partial Private Sub OnYChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnYChanged()
    End Sub
    Partial Private Sub OnColorChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnColorChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", DbType:="VarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me.OnNameChanging(value)
				Me.SendPropertyChanging
				Me._Name = value
				Me.SendPropertyChanged("Name")
				Me.OnNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_X", DbType:="Int")>  _
	Public Property X() As System.Nullable(Of Integer)
		Get
			Return Me._X
		End Get
		Set
			If (Me._X.Equals(value) = false) Then
				Me.OnXChanging(value)
				Me.SendPropertyChanging
				Me._X = value
				Me.SendPropertyChanged("X")
				Me.OnXChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Y", DbType:="Int")>  _
	Public Property Y() As System.Nullable(Of Integer)
		Get
			Return Me._Y
		End Get
		Set
			If (Me._Y.Equals(value) = false) Then
				Me.OnYChanging(value)
				Me.SendPropertyChanging
				Me._Y = value
				Me.SendPropertyChanged("Y")
				Me.OnYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Color", DbType:="Int")>  _
	Public Property Color() As System.Nullable(Of Integer)
		Get
			Return Me._Color
		End Get
		Set
			If (Me._Color.Equals(value) = false) Then
				Me.OnColorChanging(value)
				Me.SendPropertyChanging
				Me._Color = value
				Me.SendPropertyChanged("Color")
				Me.OnColorChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.[Order]")>  _
Partial Public Class [Order]
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _OrderID As String
	
	Private _StaffID As String
	
	Private _TableNo As String
	
	Private _OrderDateTime As Date
	
	Private _TotalAmount As Decimal
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnOrderIDChanging(value As String)
    End Sub
    Partial Private Sub OnOrderIDChanged()
    End Sub
    Partial Private Sub OnStaffIDChanging(value As String)
    End Sub
    Partial Private Sub OnStaffIDChanged()
    End Sub
    Partial Private Sub OnTableNoChanging(value As String)
    End Sub
    Partial Private Sub OnTableNoChanged()
    End Sub
    Partial Private Sub OnOrderDateTimeChanging(value As Date)
    End Sub
    Partial Private Sub OnOrderDateTimeChanged()
    End Sub
    Partial Private Sub OnTotalAmountChanging(value As Decimal)
    End Sub
    Partial Private Sub OnTotalAmountChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderID", DbType:="VarChar(10) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property OrderID() As String
		Get
			Return Me._OrderID
		End Get
		Set
			If (String.Equals(Me._OrderID, value) = false) Then
				Me.OnOrderIDChanging(value)
				Me.SendPropertyChanging
				Me._OrderID = value
				Me.SendPropertyChanged("OrderID")
				Me.OnOrderIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StaffID", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property StaffID() As String
		Get
			Return Me._StaffID
		End Get
		Set
			If (String.Equals(Me._StaffID, value) = false) Then
				Me.OnStaffIDChanging(value)
				Me.SendPropertyChanging
				Me._StaffID = value
				Me.SendPropertyChanged("StaffID")
				Me.OnStaffIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TableNo", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property TableNo() As String
		Get
			Return Me._TableNo
		End Get
		Set
			If (String.Equals(Me._TableNo, value) = false) Then
				Me.OnTableNoChanging(value)
				Me.SendPropertyChanging
				Me._TableNo = value
				Me.SendPropertyChanged("TableNo")
				Me.OnTableNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderDateTime", DbType:="DateTime NOT NULL")>  _
	Public Property OrderDateTime() As Date
		Get
			Return Me._OrderDateTime
		End Get
		Set
			If ((Me._OrderDateTime = value)  _
						= false) Then
				Me.OnOrderDateTimeChanging(value)
				Me.SendPropertyChanging
				Me._OrderDateTime = value
				Me.SendPropertyChanged("OrderDateTime")
				Me.OnOrderDateTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalAmount", DbType:="Decimal(10,2) NOT NULL")>  _
	Public Property TotalAmount() As Decimal
		Get
			Return Me._TotalAmount
		End Get
		Set
			If ((Me._TotalAmount = value)  _
						= false) Then
				Me.OnTotalAmountChanging(value)
				Me.SendPropertyChanging
				Me._TotalAmount = value
				Me.SendPropertyChanged("TotalAmount")
				Me.OnTotalAmountChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Order_Item")>  _
Partial Public Class Order_Item
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _OrderItemID As String
	
	Private _OrderID As String
	
	Private _Item_Id As String
	
	Private _Quantity As Integer
	
	Private _SubTotal As Decimal
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnOrderItemIDChanging(value As String)
    End Sub
    Partial Private Sub OnOrderItemIDChanged()
    End Sub
    Partial Private Sub OnOrderIDChanging(value As String)
    End Sub
    Partial Private Sub OnOrderIDChanged()
    End Sub
    Partial Private Sub OnItem_IdChanging(value As String)
    End Sub
    Partial Private Sub OnItem_IdChanged()
    End Sub
    Partial Private Sub OnQuantityChanging(value As Integer)
    End Sub
    Partial Private Sub OnQuantityChanged()
    End Sub
    Partial Private Sub OnSubTotalChanging(value As Decimal)
    End Sub
    Partial Private Sub OnSubTotalChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderItemID", DbType:="VarChar(12) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property OrderItemID() As String
		Get
			Return Me._OrderItemID
		End Get
		Set
			If (String.Equals(Me._OrderItemID, value) = false) Then
				Me.OnOrderItemIDChanging(value)
				Me.SendPropertyChanging
				Me._OrderItemID = value
				Me.SendPropertyChanged("OrderItemID")
				Me.OnOrderItemIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderID", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property OrderID() As String
		Get
			Return Me._OrderID
		End Get
		Set
			If (String.Equals(Me._OrderID, value) = false) Then
				Me.OnOrderIDChanging(value)
				Me.SendPropertyChanging
				Me._OrderID = value
				Me.SendPropertyChanged("OrderID")
				Me.OnOrderIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Id", DbType:="VarChar(7) NOT NULL", CanBeNull:=false)>  _
	Public Property Item_Id() As String
		Get
			Return Me._Item_Id
		End Get
		Set
			If (String.Equals(Me._Item_Id, value) = false) Then
				Me.OnItem_IdChanging(value)
				Me.SendPropertyChanging
				Me._Item_Id = value
				Me.SendPropertyChanged("Item_Id")
				Me.OnItem_IdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Quantity", DbType:="Int NOT NULL")>  _
	Public Property Quantity() As Integer
		Get
			Return Me._Quantity
		End Get
		Set
			If ((Me._Quantity = value)  _
						= false) Then
				Me.OnQuantityChanging(value)
				Me.SendPropertyChanging
				Me._Quantity = value
				Me.SendPropertyChanged("Quantity")
				Me.OnQuantityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubTotal", DbType:="Decimal(10,2) NOT NULL")>  _
	Public Property SubTotal() As Decimal
		Get
			Return Me._SubTotal
		End Get
		Set
			If ((Me._SubTotal = value)  _
						= false) Then
				Me.OnSubTotalChanging(value)
				Me.SendPropertyChanging
				Me._SubTotal = value
				Me.SendPropertyChanged("SubTotal")
				Me.OnSubTotalChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
