'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="BL-fariz")>  _
Partial Public Class BL_farizDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertItem(instance As Item)
    End Sub
  Partial Private Sub UpdateItem(instance As Item)
    End Sub
  Partial Private Sub DeleteItem(instance As Item)
    End Sub
  Partial Private Sub InsertOrder(instance As [Order])
    End Sub
  Partial Private Sub UpdateOrder(instance As [Order])
    End Sub
  Partial Private Sub DeleteOrder(instance As [Order])
    End Sub
  Partial Private Sub InsertOrder_Item(instance As Order_Item)
    End Sub
  Partial Private Sub UpdateOrder_Item(instance As Order_Item)
    End Sub
  Partial Private Sub DeleteOrder_Item(instance As Order_Item)
    End Sub
  Partial Private Sub InsertPayment(instance As Payment)
    End Sub
  Partial Private Sub UpdatePayment(instance As Payment)
    End Sub
  Partial Private Sub DeletePayment(instance As Payment)
    End Sub
  Partial Private Sub InsertTableNo(instance As TableNo)
    End Sub
  Partial Private Sub UpdateTableNo(instance As TableNo)
    End Sub
  Partial Private Sub DeleteTableNo(instance As TableNo)
    End Sub
  Partial Private Sub InsertStaff(instance As Staff)
    End Sub
  Partial Private Sub UpdateStaff(instance As Staff)
    End Sub
  Partial Private Sub DeleteStaff(instance As Staff)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Assignment.My.MySettings.Default.BL_FarizConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Items() As System.Data.Linq.Table(Of Item)
		Get
			Return Me.GetTable(Of Item)
		End Get
	End Property
	
	Public ReadOnly Property Orders() As System.Data.Linq.Table(Of [Order])
		Get
			Return Me.GetTable(Of [Order])
		End Get
	End Property
	
	Public ReadOnly Property Order_Items() As System.Data.Linq.Table(Of Order_Item)
		Get
			Return Me.GetTable(Of Order_Item)
		End Get
	End Property
	
	Public ReadOnly Property Payments() As System.Data.Linq.Table(Of Payment)
		Get
			Return Me.GetTable(Of Payment)
		End Get
	End Property
	
	Public ReadOnly Property TableNos() As System.Data.Linq.Table(Of TableNo)
		Get
			Return Me.GetTable(Of TableNo)
		End Get
	End Property
	
	Public ReadOnly Property Staffs() As System.Data.Linq.Table(Of Staff)
		Get
			Return Me.GetTable(Of Staff)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Item")>  _
Partial Public Class Item
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Item_Id As String
	
	Private _Item_Name As String
	
	Private _Item_Category As String
	
	Private _Item_Price As Decimal
	
	Private _Item_Description As String
	
	Private _Item_Quantity As Integer
	
	Private _Item_StockLvl As String
	
	Private _Item_Picture As System.Data.Linq.Binary
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnItem_IdChanging(value As String)
    End Sub
    Partial Private Sub OnItem_IdChanged()
    End Sub
    Partial Private Sub OnItem_NameChanging(value As String)
    End Sub
    Partial Private Sub OnItem_NameChanged()
    End Sub
    Partial Private Sub OnItem_CategoryChanging(value As String)
    End Sub
    Partial Private Sub OnItem_CategoryChanged()
    End Sub
    Partial Private Sub OnItem_PriceChanging(value As Decimal)
    End Sub
    Partial Private Sub OnItem_PriceChanged()
    End Sub
    Partial Private Sub OnItem_DescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnItem_DescriptionChanged()
    End Sub
    Partial Private Sub OnItem_QuantityChanging(value As Integer)
    End Sub
    Partial Private Sub OnItem_QuantityChanged()
    End Sub
    Partial Private Sub OnItem_StockLvlChanging(value As String)
    End Sub
    Partial Private Sub OnItem_StockLvlChanged()
    End Sub
    Partial Private Sub OnItem_PictureChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnItem_PictureChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Id", DbType:="VarChar(7) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property Item_Id() As String
		Get
			Return Me._Item_Id
		End Get
		Set
			If (String.Equals(Me._Item_Id, value) = false) Then
				Me.OnItem_IdChanging(value)
				Me.SendPropertyChanging
				Me._Item_Id = value
				Me.SendPropertyChanged("Item_Id")
				Me.OnItem_IdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Name", DbType:="VarChar(30) NOT NULL", CanBeNull:=false)>  _
	Public Property Item_Name() As String
		Get
			Return Me._Item_Name
		End Get
		Set
			If (String.Equals(Me._Item_Name, value) = false) Then
				Me.OnItem_NameChanging(value)
				Me.SendPropertyChanging
				Me._Item_Name = value
				Me.SendPropertyChanged("Item_Name")
				Me.OnItem_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Category", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property Item_Category() As String
		Get
			Return Me._Item_Category
		End Get
		Set
			If (String.Equals(Me._Item_Category, value) = false) Then
				Me.OnItem_CategoryChanging(value)
				Me.SendPropertyChanging
				Me._Item_Category = value
				Me.SendPropertyChanged("Item_Category")
				Me.OnItem_CategoryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Price", DbType:="Decimal(10,2) NOT NULL")>  _
	Public Property Item_Price() As Decimal
		Get
			Return Me._Item_Price
		End Get
		Set
			If ((Me._Item_Price = value)  _
						= false) Then
				Me.OnItem_PriceChanging(value)
				Me.SendPropertyChanging
				Me._Item_Price = value
				Me.SendPropertyChanged("Item_Price")
				Me.OnItem_PriceChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Description", DbType:="VarChar(500) NOT NULL", CanBeNull:=false)>  _
	Public Property Item_Description() As String
		Get
			Return Me._Item_Description
		End Get
		Set
			If (String.Equals(Me._Item_Description, value) = false) Then
				Me.OnItem_DescriptionChanging(value)
				Me.SendPropertyChanging
				Me._Item_Description = value
				Me.SendPropertyChanged("Item_Description")
				Me.OnItem_DescriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Quantity", DbType:="Int NOT NULL")>  _
	Public Property Item_Quantity() As Integer
		Get
			Return Me._Item_Quantity
		End Get
		Set
			If ((Me._Item_Quantity = value)  _
						= false) Then
				Me.OnItem_QuantityChanging(value)
				Me.SendPropertyChanging
				Me._Item_Quantity = value
				Me.SendPropertyChanged("Item_Quantity")
				Me.OnItem_QuantityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_StockLvl", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property Item_StockLvl() As String
		Get
			Return Me._Item_StockLvl
		End Get
		Set
			If (String.Equals(Me._Item_StockLvl, value) = false) Then
				Me.OnItem_StockLvlChanging(value)
				Me.SendPropertyChanging
				Me._Item_StockLvl = value
				Me.SendPropertyChanged("Item_StockLvl")
				Me.OnItem_StockLvlChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Picture", DbType:="VarBinary(MAX)", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Item_Picture() As System.Data.Linq.Binary
		Get
			Return Me._Item_Picture
		End Get
		Set
			If (Object.Equals(Me._Item_Picture, value) = false) Then
				Me.OnItem_PictureChanging(value)
				Me.SendPropertyChanging
				Me._Item_Picture = value
				Me.SendPropertyChanged("Item_Picture")
				Me.OnItem_PictureChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.[Order]")>  _
Partial Public Class [Order]
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _OrderID As String
	
	Private _StaffID As String
	
	Private _TableNo As String
	
	Private _OrderDateTime As Date
	
	Private _TotalAmount As Decimal
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnOrderIDChanging(value As String)
    End Sub
    Partial Private Sub OnOrderIDChanged()
    End Sub
    Partial Private Sub OnStaffIDChanging(value As String)
    End Sub
    Partial Private Sub OnStaffIDChanged()
    End Sub
    Partial Private Sub OnTableNoChanging(value As String)
    End Sub
    Partial Private Sub OnTableNoChanged()
    End Sub
    Partial Private Sub OnOrderDateTimeChanging(value As Date)
    End Sub
    Partial Private Sub OnOrderDateTimeChanged()
    End Sub
    Partial Private Sub OnTotalAmountChanging(value As Decimal)
    End Sub
    Partial Private Sub OnTotalAmountChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderID", DbType:="VarChar(10) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property OrderID() As String
		Get
			Return Me._OrderID
		End Get
		Set
			If (String.Equals(Me._OrderID, value) = false) Then
				Me.OnOrderIDChanging(value)
				Me.SendPropertyChanging
				Me._OrderID = value
				Me.SendPropertyChanged("OrderID")
				Me.OnOrderIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StaffID", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property StaffID() As String
		Get
			Return Me._StaffID
		End Get
		Set
			If (String.Equals(Me._StaffID, value) = false) Then
				Me.OnStaffIDChanging(value)
				Me.SendPropertyChanging
				Me._StaffID = value
				Me.SendPropertyChanged("StaffID")
				Me.OnStaffIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TableNo", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property TableNo() As String
		Get
			Return Me._TableNo
		End Get
		Set
			If (String.Equals(Me._TableNo, value) = false) Then
				Me.OnTableNoChanging(value)
				Me.SendPropertyChanging
				Me._TableNo = value
				Me.SendPropertyChanged("TableNo")
				Me.OnTableNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderDateTime", DbType:="DateTime NOT NULL")>  _
	Public Property OrderDateTime() As Date
		Get
			Return Me._OrderDateTime
		End Get
		Set
			If ((Me._OrderDateTime = value)  _
						= false) Then
				Me.OnOrderDateTimeChanging(value)
				Me.SendPropertyChanging
				Me._OrderDateTime = value
				Me.SendPropertyChanged("OrderDateTime")
				Me.OnOrderDateTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalAmount", DbType:="Decimal(10,2) NOT NULL")>  _
	Public Property TotalAmount() As Decimal
		Get
			Return Me._TotalAmount
		End Get
		Set
			If ((Me._TotalAmount = value)  _
						= false) Then
				Me.OnTotalAmountChanging(value)
				Me.SendPropertyChanging
				Me._TotalAmount = value
				Me.SendPropertyChanged("TotalAmount")
				Me.OnTotalAmountChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Order_Item")>  _
Partial Public Class Order_Item
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _OrderItemID As String
	
	Private _OrderID As String
	
	Private _Item_Id As String
	
	Private _Quantity As Integer
	
	Private _SubTotal As Decimal
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnOrderItemIDChanging(value As String)
    End Sub
    Partial Private Sub OnOrderItemIDChanged()
    End Sub
    Partial Private Sub OnOrderIDChanging(value As String)
    End Sub
    Partial Private Sub OnOrderIDChanged()
    End Sub
    Partial Private Sub OnItem_IdChanging(value As String)
    End Sub
    Partial Private Sub OnItem_IdChanged()
    End Sub
    Partial Private Sub OnQuantityChanging(value As Integer)
    End Sub
    Partial Private Sub OnQuantityChanged()
    End Sub
    Partial Private Sub OnSubTotalChanging(value As Decimal)
    End Sub
    Partial Private Sub OnSubTotalChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderItemID", DbType:="VarChar(12) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property OrderItemID() As String
		Get
			Return Me._OrderItemID
		End Get
		Set
			If (String.Equals(Me._OrderItemID, value) = false) Then
				Me.OnOrderItemIDChanging(value)
				Me.SendPropertyChanging
				Me._OrderItemID = value
				Me.SendPropertyChanged("OrderItemID")
				Me.OnOrderItemIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderID", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property OrderID() As String
		Get
			Return Me._OrderID
		End Get
		Set
			If (String.Equals(Me._OrderID, value) = false) Then
				Me.OnOrderIDChanging(value)
				Me.SendPropertyChanging
				Me._OrderID = value
				Me.SendPropertyChanged("OrderID")
				Me.OnOrderIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Item_Id", DbType:="VarChar(7) NOT NULL", CanBeNull:=false)>  _
	Public Property Item_Id() As String
		Get
			Return Me._Item_Id
		End Get
		Set
			If (String.Equals(Me._Item_Id, value) = false) Then
				Me.OnItem_IdChanging(value)
				Me.SendPropertyChanging
				Me._Item_Id = value
				Me.SendPropertyChanged("Item_Id")
				Me.OnItem_IdChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Quantity", DbType:="Int NOT NULL")>  _
	Public Property Quantity() As Integer
		Get
			Return Me._Quantity
		End Get
		Set
			If ((Me._Quantity = value)  _
						= false) Then
				Me.OnQuantityChanging(value)
				Me.SendPropertyChanging
				Me._Quantity = value
				Me.SendPropertyChanged("Quantity")
				Me.OnQuantityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SubTotal", DbType:="Decimal(10,2) NOT NULL")>  _
	Public Property SubTotal() As Decimal
		Get
			Return Me._SubTotal
		End Get
		Set
			If ((Me._SubTotal = value)  _
						= false) Then
				Me.OnSubTotalChanging(value)
				Me.SendPropertyChanging
				Me._SubTotal = value
				Me.SendPropertyChanged("SubTotal")
				Me.OnSubTotalChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Payment")>  _
Partial Public Class Payment
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _PaymentID As String
	
	Private _OrderID As String
	
	Private _PaymentMethod As String
	
	Private _AmountPaid As Decimal
	
	Private _DateTime As System.Nullable(Of Date)
	
	Private _PaymentStatus As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnPaymentIDChanging(value As String)
    End Sub
    Partial Private Sub OnPaymentIDChanged()
    End Sub
    Partial Private Sub OnOrderIDChanging(value As String)
    End Sub
    Partial Private Sub OnOrderIDChanged()
    End Sub
    Partial Private Sub OnPaymentMethodChanging(value As String)
    End Sub
    Partial Private Sub OnPaymentMethodChanged()
    End Sub
    Partial Private Sub OnAmountPaidChanging(value As Decimal)
    End Sub
    Partial Private Sub OnAmountPaidChanged()
    End Sub
    Partial Private Sub OnDateTimeChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnDateTimeChanged()
    End Sub
    Partial Private Sub OnPaymentStatusChanging(value As String)
    End Sub
    Partial Private Sub OnPaymentStatusChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PaymentID", DbType:="VarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property PaymentID() As String
		Get
			Return Me._PaymentID
		End Get
		Set
			If (String.Equals(Me._PaymentID, value) = false) Then
				Me.OnPaymentIDChanging(value)
				Me.SendPropertyChanging
				Me._PaymentID = value
				Me.SendPropertyChanged("PaymentID")
				Me.OnPaymentIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderID", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property OrderID() As String
		Get
			Return Me._OrderID
		End Get
		Set
			If (String.Equals(Me._OrderID, value) = false) Then
				Me.OnOrderIDChanging(value)
				Me.SendPropertyChanging
				Me._OrderID = value
				Me.SendPropertyChanged("OrderID")
				Me.OnOrderIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PaymentMethod", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property PaymentMethod() As String
		Get
			Return Me._PaymentMethod
		End Get
		Set
			If (String.Equals(Me._PaymentMethod, value) = false) Then
				Me.OnPaymentMethodChanging(value)
				Me.SendPropertyChanging
				Me._PaymentMethod = value
				Me.SendPropertyChanged("PaymentMethod")
				Me.OnPaymentMethodChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AmountPaid", DbType:="Decimal(10,2) NOT NULL")>  _
	Public Property AmountPaid() As Decimal
		Get
			Return Me._AmountPaid
		End Get
		Set
			If ((Me._AmountPaid = value)  _
						= false) Then
				Me.OnAmountPaidChanging(value)
				Me.SendPropertyChanging
				Me._AmountPaid = value
				Me.SendPropertyChanged("AmountPaid")
				Me.OnAmountPaidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateTime", DbType:="DateTime")>  _
	Public Property DateTime() As System.Nullable(Of Date)
		Get
			Return Me._DateTime
		End Get
		Set
			If (Me._DateTime.Equals(value) = false) Then
				Me.OnDateTimeChanging(value)
				Me.SendPropertyChanging
				Me._DateTime = value
				Me.SendPropertyChanged("DateTime")
				Me.OnDateTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PaymentStatus", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property PaymentStatus() As String
		Get
			Return Me._PaymentStatus
		End Get
		Set
			If (String.Equals(Me._PaymentStatus, value) = false) Then
				Me.OnPaymentStatusChanging(value)
				Me.SendPropertyChanging
				Me._PaymentStatus = value
				Me.SendPropertyChanged("PaymentStatus")
				Me.OnPaymentStatusChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.TableNo")>  _
Partial Public Class TableNo
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _Name As String
	
	Private _X As System.Nullable(Of Integer)
	
	Private _Y As System.Nullable(Of Integer)
	
	Private _Color As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnNameChanging(value As String)
    End Sub
    Partial Private Sub OnNameChanged()
    End Sub
    Partial Private Sub OnXChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnXChanged()
    End Sub
    Partial Private Sub OnYChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnYChanged()
    End Sub
    Partial Private Sub OnColorChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnColorChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", DbType:="VarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me.OnNameChanging(value)
				Me.SendPropertyChanging
				Me._Name = value
				Me.SendPropertyChanged("Name")
				Me.OnNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_X", DbType:="Int")>  _
	Public Property X() As System.Nullable(Of Integer)
		Get
			Return Me._X
		End Get
		Set
			If (Me._X.Equals(value) = false) Then
				Me.OnXChanging(value)
				Me.SendPropertyChanging
				Me._X = value
				Me.SendPropertyChanged("X")
				Me.OnXChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Y", DbType:="Int")>  _
	Public Property Y() As System.Nullable(Of Integer)
		Get
			Return Me._Y
		End Get
		Set
			If (Me._Y.Equals(value) = false) Then
				Me.OnYChanging(value)
				Me.SendPropertyChanging
				Me._Y = value
				Me.SendPropertyChanged("Y")
				Me.OnYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Color", DbType:="Int")>  _
	Public Property Color() As System.Nullable(Of Integer)
		Get
			Return Me._Color
		End Get
		Set
			If (Me._Color.Equals(value) = false) Then
				Me.OnColorChanging(value)
				Me.SendPropertyChanging
				Me._Color = value
				Me.SendPropertyChanged("Color")
				Me.OnColorChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Staff")>  _
Partial Public Class Staff
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _StaffID As String
	
	Private _FirstName As String
	
	Private _LastName As String
	
	Private _Gender As String
	
	Private _ContactNumber As String
	
	Private _EmailAddress As String
	
	Private _HomeAddress As String
	
	Private _ProfileImage As System.Data.Linq.Binary
	
	Private _Department As String
	
	Private _Role As String
	
	Private _Username As String
	
	Private _Password As String
	
	Private _CreatedDate As System.Nullable(Of Date)
	
	Private _Status As String
	
	Private _CreatedBy As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnStaffIDChanging(value As String)
    End Sub
    Partial Private Sub OnStaffIDChanged()
    End Sub
    Partial Private Sub OnFirstNameChanging(value As String)
    End Sub
    Partial Private Sub OnFirstNameChanged()
    End Sub
    Partial Private Sub OnLastNameChanging(value As String)
    End Sub
    Partial Private Sub OnLastNameChanged()
    End Sub
    Partial Private Sub OnGenderChanging(value As String)
    End Sub
    Partial Private Sub OnGenderChanged()
    End Sub
    Partial Private Sub OnContactNumberChanging(value As String)
    End Sub
    Partial Private Sub OnContactNumberChanged()
    End Sub
    Partial Private Sub OnEmailAddressChanging(value As String)
    End Sub
    Partial Private Sub OnEmailAddressChanged()
    End Sub
    Partial Private Sub OnHomeAddressChanging(value As String)
    End Sub
    Partial Private Sub OnHomeAddressChanged()
    End Sub
    Partial Private Sub OnProfileImageChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnProfileImageChanged()
    End Sub
    Partial Private Sub OnDepartmentChanging(value As String)
    End Sub
    Partial Private Sub OnDepartmentChanged()
    End Sub
    Partial Private Sub OnRoleChanging(value As String)
    End Sub
    Partial Private Sub OnRoleChanged()
    End Sub
    Partial Private Sub OnUsernameChanging(value As String)
    End Sub
    Partial Private Sub OnUsernameChanged()
    End Sub
    Partial Private Sub OnPasswordChanging(value As String)
    End Sub
    Partial Private Sub OnPasswordChanged()
    End Sub
    Partial Private Sub OnCreatedDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCreatedDateChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As String)
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnCreatedByChanging(value As String)
    End Sub
    Partial Private Sub OnCreatedByChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StaffID", DbType:="Char(5) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property StaffID() As String
		Get
			Return Me._StaffID
		End Get
		Set
			If (String.Equals(Me._StaffID, value) = false) Then
				Me.OnStaffIDChanging(value)
				Me.SendPropertyChanging
				Me._StaffID = value
				Me.SendPropertyChanged("StaffID")
				Me.OnStaffIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FirstName", DbType:="VarChar(30)")>  _
	Public Property FirstName() As String
		Get
			Return Me._FirstName
		End Get
		Set
			If (String.Equals(Me._FirstName, value) = false) Then
				Me.OnFirstNameChanging(value)
				Me.SendPropertyChanging
				Me._FirstName = value
				Me.SendPropertyChanged("FirstName")
				Me.OnFirstNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LastName", DbType:="VarChar(30)")>  _
	Public Property LastName() As String
		Get
			Return Me._LastName
		End Get
		Set
			If (String.Equals(Me._LastName, value) = false) Then
				Me.OnLastNameChanging(value)
				Me.SendPropertyChanging
				Me._LastName = value
				Me.SendPropertyChanged("LastName")
				Me.OnLastNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Gender", DbType:="VarChar(6)")>  _
	Public Property Gender() As String
		Get
			Return Me._Gender
		End Get
		Set
			If (String.Equals(Me._Gender, value) = false) Then
				Me.OnGenderChanging(value)
				Me.SendPropertyChanging
				Me._Gender = value
				Me.SendPropertyChanged("Gender")
				Me.OnGenderChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ContactNumber", DbType:="VarChar(15)")>  _
	Public Property ContactNumber() As String
		Get
			Return Me._ContactNumber
		End Get
		Set
			If (String.Equals(Me._ContactNumber, value) = false) Then
				Me.OnContactNumberChanging(value)
				Me.SendPropertyChanging
				Me._ContactNumber = value
				Me.SendPropertyChanged("ContactNumber")
				Me.OnContactNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmailAddress", DbType:="VarChar(254)")>  _
	Public Property EmailAddress() As String
		Get
			Return Me._EmailAddress
		End Get
		Set
			If (String.Equals(Me._EmailAddress, value) = false) Then
				Me.OnEmailAddressChanging(value)
				Me.SendPropertyChanging
				Me._EmailAddress = value
				Me.SendPropertyChanged("EmailAddress")
				Me.OnEmailAddressChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HomeAddress", DbType:="VarChar(999)")>  _
	Public Property HomeAddress() As String
		Get
			Return Me._HomeAddress
		End Get
		Set
			If (String.Equals(Me._HomeAddress, value) = false) Then
				Me.OnHomeAddressChanging(value)
				Me.SendPropertyChanging
				Me._HomeAddress = value
				Me.SendPropertyChanged("HomeAddress")
				Me.OnHomeAddressChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ProfileImage", DbType:="VarBinary(MAX)", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property ProfileImage() As System.Data.Linq.Binary
		Get
			Return Me._ProfileImage
		End Get
		Set
			If (Object.Equals(Me._ProfileImage, value) = false) Then
				Me.OnProfileImageChanging(value)
				Me.SendPropertyChanging
				Me._ProfileImage = value
				Me.SendPropertyChanged("ProfileImage")
				Me.OnProfileImageChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Department", DbType:="VarChar(21)")>  _
	Public Property Department() As String
		Get
			Return Me._Department
		End Get
		Set
			If (String.Equals(Me._Department, value) = false) Then
				Me.OnDepartmentChanging(value)
				Me.SendPropertyChanging
				Me._Department = value
				Me.SendPropertyChanged("Department")
				Me.OnDepartmentChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Role", DbType:="VarChar(15)")>  _
	Public Property Role() As String
		Get
			Return Me._Role
		End Get
		Set
			If (String.Equals(Me._Role, value) = false) Then
				Me.OnRoleChanging(value)
				Me.SendPropertyChanging
				Me._Role = value
				Me.SendPropertyChanged("Role")
				Me.OnRoleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Username", DbType:="VarChar(25)")>  _
	Public Property Username() As String
		Get
			Return Me._Username
		End Get
		Set
			If (String.Equals(Me._Username, value) = false) Then
				Me.OnUsernameChanging(value)
				Me.SendPropertyChanging
				Me._Username = value
				Me.SendPropertyChanged("Username")
				Me.OnUsernameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Password", DbType:="VarChar(25)")>  _
	Public Property Password() As String
		Get
			Return Me._Password
		End Get
		Set
			If (String.Equals(Me._Password, value) = false) Then
				Me.OnPasswordChanging(value)
				Me.SendPropertyChanging
				Me._Password = value
				Me.SendPropertyChanged("Password")
				Me.OnPasswordChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedDate", DbType:="DateTime")>  _
	Public Property CreatedDate() As System.Nullable(Of Date)
		Get
			Return Me._CreatedDate
		End Get
		Set
			If (Me._CreatedDate.Equals(value) = false) Then
				Me.OnCreatedDateChanging(value)
				Me.SendPropertyChanging
				Me._CreatedDate = value
				Me.SendPropertyChanged("CreatedDate")
				Me.OnCreatedDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="VarChar(8)")>  _
	Public Property Status() As String
		Get
			Return Me._Status
		End Get
		Set
			If (String.Equals(Me._Status, value) = false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreatedBy", DbType:="VarChar(90)")>  _
	Public Property CreatedBy() As String
		Get
			Return Me._CreatedBy
		End Get
		Set
			If (String.Equals(Me._CreatedBy, value) = false) Then
				Me.OnCreatedByChanging(value)
				Me.SendPropertyChanging
				Me._CreatedBy = value
				Me.SendPropertyChanged("CreatedBy")
				Me.OnCreatedByChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
